#!/bin/bash

echo "🧪 Address Book Test Script"
echo "=========================="
echo ""
echo "📋 Test Instructions:"
echo ""
echo "1. Start your Vite app:"
echo "   npm run dev"
echo ""
echo "2. Login to your account"
echo ""
echo "3. Open the Address Book page:"
echo "   http://localhost:5173/addresses"
echo ""
echo "4. Open browser console (F12) and run:"
echo "   - viewAddresses() - View all addresses"
echo "   - addTestAddress() - Add a test address"
echo "   - addMultipleTestAddresses() - Add 3 test addresses"
echo "   - clearAddresses() - Clear all addresses"
echo ""
echo "5. Test the UI:"
echo "   ✅ Add Address"
echo "   ✅ Edit Address"
echo "   ✅ Delete Address"
echo "   ✅ Set Default Address"
echo "   ✅ Select Address"
echo ""
echo "6. Check localStorage:"
echo "   F12 → Application → Local Storage → http://localhost:5173"
echo "   Look for: addresses_{user_id}"
echo ""
echo "📝 Bug Report Template:"
echo "   - Test Case: [What failed]"
echo "   - Expected: [What should happen]"
echo "   - Actual: [What happened]"
echo "   - Screenshot: [Take one]"
echo "   - Browser: [Chrome/Firefox/etc]"
echo ""
echo "✅ Test script ready!"
