import { Product } from './productService';

export const womensFashionProducts: Product[] = [
  {
    id: 'w1',
    name: 'Floral Summer Dress',
    price: 49.99,
    oldPrice: 79.99,
    image: 'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=400&h=500&fit=crop',
    category: 'Clothing',
    categoryId: 1,
    gender: 'women',
    brand: 'Zara',
    brandId: 3,
    rating: 4.5,
    reviews: 128,
    badge: 'SALE',
    badgeColor: 'red',
    isNew: false,
    isTrending: true,
    isSale: true,
    description: 'Beautiful floral dress perfect for summer days',
    createdAt: new Date('2024-05-01'),
  },
  {
    id: 'w2',
    name: 'Elegant Evening Gown',
    price: 129.99,
    oldPrice: 199.99,
    image: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=400&h=500&fit=crop',
    category: 'Clothing',
    categoryId: 1,
    gender: 'women',
    brand: 'KAFFE',
    brandId: 9,
    rating: 4.8,
    reviews: 89,
    badge: 'DESIGNER',
    badgeColor: 'purple',
    isNew: true,
    isTrending: true,
    isSale: true,
    description: 'Stunning evening gown for special occasions',
    createdAt: new Date('2024-06-01'),
  },
  {
    id: 'w3',
    name: 'Wool Blend Coat',
    price: 159.99,
    oldPrice: 249.99,
    image: 'https://images.unsplash.com/photo-1539533113208-f6df8cc8b543?w=400&h=500&fit=crop',
    category: 'Clothing',
    categoryId: 1,
    gender: 'women',
    brand: 'HUGO',
    brandId: 10,
    rating: 4.7,
    reviews: 156,
    badge: 'SALE',
    badgeColor: 'red',
    isNew: false,
    isTrending: true,
    isSale: true,
    description: 'Elegant wool blend coat for winter',
    createdAt: new Date('2024-04-15'),
  },
  {
    id: 'w4',
    name: 'Silk Blouse',
    price: 89.99,
    image: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=400&h=500&fit=crop',
    category: 'Clothing',
    categoryId: 1,
    gender: 'women',
    brand: 'SAMSØE SAMSØE',
    brandId: 12,
    rating: 4.6,
    reviews: 234,
    badge: 'NEW',
    badgeColor: 'green',
    isNew: true,
    isTrending: true,
    isSale: false,
    description: 'Luxurious silk blouse',
    createdAt: new Date('2024-06-10'),
  },
  {
    id: 'w5',
    name: 'Designer Handbag',
    price: 299.99,
    oldPrice: 499.99,
    image: 'https://images.unsplash.com/photo-1584917865445-de89df76afd3?w=400&h=500&fit=crop',
    category: 'Accessories',
    categoryId: 3,
    gender: 'women',
    brand: 'Gucci',
    brandId: 5,
    rating: 4.9,
    reviews: 45,
    badge: 'LUXURY',
    badgeColor: 'gold',
    isNew: true,
    isTrending: true,
    isSale: true,
    description: 'Designer handbag from Gucci',
    createdAt: new Date('2024-06-05'),
  },
  {
    id: 'w6',
    name: 'Leather Boots',
    price: 189.99,
    oldPrice: 279.99,
    image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=400&h=500&fit=crop',
    category: 'Shoes',
    categoryId: 2,
    gender: 'women',
    brand: 'Calvin Klein',
    brandId: 8,
    rating: 4.7,
    reviews: 178,
    badge: 'SALE',
    badgeColor: 'red',
    isNew: false,
    isTrending: true,
    isSale: true,
    description: 'Stylish leather boots',
    createdAt: new Date('2024-05-20'),
  },
];
